FROM golang:1.25.0-alpine3.22

ARG \
  APP_NAME=$1

ENV \
  CGO_ENABLED=0 \
  GOOS=linux \
  GOARCH=amd64

WORKDIR /app

COPY go.mod /app/go.mod
COPY go.sum /app/go.sum
COPY /${APP_NAME}/main.go /app/main.go
COPY utils /app/utils

RUN go mod download

RUN go build -ldflags "-s -w" -o /app/main -buildvcs=false

CMD ["sh", "-c", "/app/main"]