FROM golang:1.23.6-alpine3.21

WORKDIR /annotation-check

COPY go.mod /annotation-check/go.mod
COPY go.sum /annotation-check/go.sum
COPY /annotation-check/main.go /annotation-check/main.go
COPY utils /annotation-check/utils

RUN go mod download

RUN go build -ldflags "-s -w" -o /go/bin/main -buildvcs=false

CMD ["sh", "-c", "main"]